[stripe]
publicKey = ""
secretKey = ""
monthlyProductId = ""
endpointSecret = ""
monthlyProductId = ""
predefinedPrices = [
    # {interval: "one-time", amount: 100, id: 'price_...'}
]

[server]
port = 3000
corsAny = false
realIpHeader = ""

[mautic]
url = ""
username = ""
password = ""