[stripe]
publicKey = ""
secretKey = ""
monthlyProductId = ""
endpointSecret = ""
monthlyProductId = ""

[server]
port = 3000
corsAny = false
realIpHeader = ""

[mautic]
url = ""
username = ""
password = ""